//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to delete this account..
        /// </summary>
        public static string Account_DeletePermissionDenied {
            get {
                return ResourceManager.GetString("Account_DeletePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit this account..
        /// </summary>
        public static string Account_EditPermissionDenied {
            get {
                return ResourceManager.GetString("Account_EditPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        public static string Account_NotFound {
            get {
                return ResourceManager.GetString("Account_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this account..
        /// </summary>
        public static string Account_ViewPermissionDenied {
            get {
                return ResourceManager.GetString("Account_ViewPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already taken..
        /// </summary>
        public static string Auth_EmailIsAlreadyTaken {
            get {
                return ResourceManager.GetString("Auth_EmailIsAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed, check your mailbox..
        /// </summary>
        public static string Auth_EmailNotConfirmed {
            get {
                return ResourceManager.GetString("Auth_EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token has expired..
        /// </summary>
        public static string Auth_ExpiredRefreshToken {
            get {
                return ResourceManager.GetString("Auth_ExpiredRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string Auth_InvalidRefreshToken {
            get {
                return ResourceManager.GetString("Auth_InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change failed..
        /// </summary>
        public static string Auth_PasswordChangeFailed {
            get {
                return ResourceManager.GetString("Auth_PasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are the same..
        /// </summary>
        public static string Auth_PasswordsAreTheSame {
            get {
                return ResourceManager.GetString("Auth_PasswordsAreTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string Auth_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Auth_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect previous password..
        /// </summary>
        public static string Auth_WrongPreviousPassword {
            get {
                return ResourceManager.GetString("Auth_WrongPreviousPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to delete this category..
        /// </summary>
        public static string Category_DeletePermissionDenied {
            get {
                return ResourceManager.GetString("Category_DeletePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit this category..
        /// </summary>
        public static string Category_EditPermissionDenied {
            get {
                return ResourceManager.GetString("Category_EditPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found..
        /// </summary>
        public static string Category_NotFound {
            get {
                return ResourceManager.GetString("Category_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this category..
        /// </summary>
        public static string Category_ViewPermissionDenied {
            get {
                return ResourceManager.GetString("Category_ViewPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmEmail-en-US.html.
        /// </summary>
        public static string EmailConfirmation_html {
            get {
                return ResourceManager.GetString("EmailConfirmation_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email confirmation token is invalid..
        /// </summary>
        public static string EmailConfirmation_InvalidToken {
            get {
                return ResourceManager.GetString("EmailConfirmation_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email address..
        /// </summary>
        public static string EmailConfirmation_Subject {
            get {
                return ResourceManager.GetString("EmailConfirmation_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit (0–9)..
        /// </summary>
        public static string PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter (a–z)..
        /// </summary>
        public static string PasswordRequiresLower {
            get {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one non-alphanumeric character..
        /// </summary>
        public static string PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one unique character..
        /// </summary>
        public static string PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter (A–Z)..
        /// </summary>
        public static string PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters..
        /// </summary>
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPassword-en-US.html.
        /// </summary>
        public static string ResetPassword_html {
            get {
                return ResourceManager.GetString("ResetPassword_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset password token is invalid..
        /// </summary>
        public static string ResetPassword_InvalidToken {
            get {
                return ResourceManager.GetString("ResetPassword_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset link has been sent to your email..
        /// </summary>
        public static string ResetPassword_LinkWasSent {
            get {
                return ResourceManager.GetString("ResetPassword_LinkWasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string ResetPassword_Subject {
            get {
                return ResourceManager.GetString("ResetPassword_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully..
        /// </summary>
        public static string ResetPassword_Success {
            get {
                return ResourceManager.GetString("ResetPassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are insufficient funds in the provided account..
        /// </summary>
        public static string Transaction_InsufficientFunds {
            get {
                return ResourceManager.GetString("Transaction_InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction not found..
        /// </summary>
        public static string Transaction_NotFound {
            get {
                return ResourceManager.GetString("Transaction_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to delete admin user but it is not allowed..
        /// </summary>
        public static string User_DeleteAdminNotAllowed {
            get {
                return ResourceManager.GetString("User_DeleteAdminNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user..
        /// </summary>
        public static string User_DeleteFailed {
            get {
                return ResourceManager.GetString("User_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent a confirmation email. Please verify your email to activate your account..
        /// </summary>
        public static string User_Registered {
            get {
                return ResourceManager.GetString("User_Registered", resourceCulture);
            }
        }
    }
}
